

//import com.sun.jdi.connect.spi.Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Joji
 */
public class AdminStudentRegistration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public AdminStudentRegistration() {
        initComponents();
        show_user();
    }
  //  Connection con;
    Connection con;
    PreparedStatement pst,pst1;
    ResultSet rs,rs1;
    //Statement stmt = null;
    
        public ArrayList<User1> userList(){
        ArrayList<User1> userslist1 =new ArrayList<>();
        try{
            con= DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
            
            PreparedStatement pst1 = con.prepareStatement("select * from users"+"&useUnicode=true&characterEncoding=UTF-8");
            rs= pst1.executeQuery();
            User1 user1;
            //userslist.add(user);
                while(rs.next()){
                    user1 =new User1(
                            rs.getInt("reg_number"),
                            rs.getString("first_name"),
                            rs.getString("last_name"),
                            rs.getString("course"));
                    userslist1.add(user1);
                    
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return userslist1;
    }
        
         public void show_user(){
          ArrayList<User1> list = userList();
          DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
          Object[] row = new Object[5];
          for(int i=0;i<list.size();i++){
              row[0] = list.get(i).getReg_numeber();
              row[1] = list.get(i).getFirstname();
              row[2] = list.get(i).getLastname();
              row[3] = list.get(i).getCourse();
              model.addRow(row);
              tbl2.revalidate();
              tbl2.repaint();
          }
          
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userFirst = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userSec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usrReg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        usrConfirm = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        usrCourse = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchby = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Student Registration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firstname");

        userFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFirstActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lastname");

        userSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registration number");

        usrReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrRegActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");

        usrConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrConfirmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course");

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search");

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl2.setForeground(new java.awt.Color(102, 102, 255));
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg Number", "First Name", "Last Name", "Course"
            }
        ));
        tbl2.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbl2);
        tbl2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(searchby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(usrCourse, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usrConfirm, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userPass, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userSec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(usrReg))))))
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(searchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(userFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(userSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(usrReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(usrConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(usrCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
            // TODO add your handling code here:
            if(searchby.getText().length() == 0 || userFirst.getText().length() ==0 || userSec.getText().length() == 0 || usrCourse.getText().length() == 0){
                JOptionPane.showMessageDialog(this, "Enter students details to delete");
            }else{
                Class.forName("com.mysql.cj.jdbc.Driver");
            int search_by = Integer.parseInt(searchby.getText());
            
                    String username=userFirst.getText();
                String lastname=userSec.getText();       
        String Course =usrCourse.getText();
            con= DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
            PreparedStatement pst = con.prepareStatement("select * from users where reg_number = "+search_by+"");
             rs=(ResultSet) pst.executeQuery();
             
             if(rs.next()){
                int result = JOptionPane.showConfirmDialog(this,"SURE!,You want to delete?","DELETE!r",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    PreparedStatement pst1 = con.prepareStatement("delete from users where reg_number =?");
                    pst1.setString(1, rs.getString("reg_number"));
                    pst1.executeUpdate();



                    JOptionPane.showMessageDialog(this, "Delete Successful");

                    searchby.setText("");
                    userFirst.setText("");
                    userSec.setText("");
                    usrCourse.setText("");
                    usrReg.setText("");
                      DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
                model.setRowCount(0);
                show_user();
                }
                
             }else{
                 JOptionPane.showMessageDialog(this, "Student Doesnt exist.Please register to edit !");
             }
            
            }
            
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddMarks md=new AddMarks();
        md.setVisible(true);// TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(userFirst.getText().length()==0){
    JOptionPane.showMessageDialog(this,"All Fields Required");
    
}
else if(userSec.getText().length()==0){
    JOptionPane.showMessageDialog(this,"All Fields Required");
}
else if (usrConfirm.getText().equals(userPass.getText())==false){
    JOptionPane.showMessageDialog(this, "Passwords do not match!");
}
else{
  //  Connection con = MyConnection.getConnection();
    
    try {
        String username=userFirst.getText();
        String lastname=userSec.getText();
        String Registrationnumber= usrReg.getText();//.(2, lastname);
        String userPasswd=userPass.getText();        
        String Course =usrCourse.getText();

        
        Class.forName("com.mysql.cj.jdbc.Driver");
        con= DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
        //con = DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
        //pst=con.prepareStatement("insert into user(Firstname,Lastname,StudentRegistration number,Password)values(?,?,?,?)");
        //pst= con.prepareStatement("insert into user(student_id,Firstname,Lastname,Password,StudentRegistration number,Course),values(?,?,?,?,?)");
        PreparedStatement pst = con.prepareStatement("insert into users values(?,?,?,?,?)");
        
        pst.setString(1, Registrationnumber);
        pst.setString(2, username);
        pst.setString(3, lastname);
        pst.setString(4, Course);        
        pst.setString(5, userPasswd);
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Registration Successiful !");
                     searchby.setText("");
                    userFirst.setText("");
                    userSec.setText("");
                    usrCourse.setText("");
                    usrReg.setText("");
                    userPass.setText("");
                    usrConfirm.setText("");
                     DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
                model.setRowCount(0);
                show_user();
        
        
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void usrRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrRegActionPerformed

    private void userSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSecActionPerformed

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void userFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFirstActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(searchby.getText().length() == 0){
                JOptionPane.showMessageDialog(this, "Field required !");
            }else{
            int search_by = Integer.parseInt(searchby.getText());
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
            PreparedStatement pst = con.prepareStatement("select * from users where reg_number = "+search_by+"");
             rs=(ResultSet) pst.executeQuery();
            if(rs.next()){
                userFirst.setText(rs.getString("first_name"));
                userSec.setText(rs.getString("last_name"));
                usrReg.setText(rs.getString("reg_number"));
                usrCourse.setText(rs.getString("course"));
            }else{
                 JOptionPane.showMessageDialog(this, "Student Not Founds !");
                 searchby.setText("");
                userFirst.setText("");
                userSec.setText("");
                usrCourse.setText("");
                usrReg.setText("");
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            if(searchby.getText().length() == 0 || userFirst.getText().length() ==0 || userSec.getText().length() == 0 || usrCourse.getText().length() == 0){
                JOptionPane.showMessageDialog(this, "All Field required !");
            }else{
                Class.forName("com.mysql.cj.jdbc.Driver");
            int search_by = Integer.parseInt(searchby.getText());
            
                    String username=userFirst.getText();
                String lastname=userSec.getText();       
        String Course =usrCourse.getText();
            con= DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
            PreparedStatement pst = con.prepareStatement("select * from users where reg_number = "+search_by+"");
             rs=(ResultSet) pst.executeQuery();
             
             if(rs.next()){
                   int result = JOptionPane.showConfirmDialog(this,"SURE!,You want to update\n?","UPDATE",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                 if(result == JOptionPane.YES_OPTION){
                PreparedStatement pst1 = con.prepareStatement("update users set first_name = ?, last_name = ? ,course = ? where reg_number =?");
                pst1.setString(1, username);
                pst1.setString(2, lastname);
                pst1.setString(3, Course);
                pst1.setString(4, rs.getString("reg_number"));
                pst1.executeUpdate();
                
 
                
                JOptionPane.showMessageDialog(this, "Update Successful");
                
                searchby.setText("");
                userFirst.setText("");
                userSec.setText("");
                usrCourse.setText("");
                usrReg.setText("");
                DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
                model.setRowCount(0);
                show_user();
                 }
                
             }else{
                 JOptionPane.showMessageDialog(this, "Student Doesnt exist.Please register to edit !");
             }
            
            }
            
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminStudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void usrConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStudentRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchby;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField userFirst;
    private javax.swing.JPasswordField userPass;
    private javax.swing.JTextField userSec;
    private javax.swing.JPasswordField usrConfirm;
    private javax.swing.JTextField usrCourse;
    private javax.swing.JTextField usrReg;
    // End of variables declaration//GEN-END:variables
}
